package FileSystemApp;


/**
* FileSystemApp/DisFileSever.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DisFileAPP.idl
* Monday, December 7, 2020 4:33:59 AM EST
*/

public interface DisFileSever extends DisFileSeverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DisFileSever
