package FileSystemApp;

/**
* FileSystemApp/DisFileClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DisFileAPP.idl
* Monday, December 7, 2020 4:33:59 AM EST
*/

public final class DisFileClientHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.DisFileClient value = null;

  public DisFileClientHolder ()
  {
  }

  public DisFileClientHolder (FileSystemApp.DisFileClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.DisFileClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.DisFileClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.DisFileClientHelper.type ();
  }

}
