package FileSystemApp;

/**
* FileSystemApp/DisFileSeverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DisFileAPP.idl
* Monday, December 7, 2020 4:33:59 AM EST
*/

public final class DisFileSeverHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystemApp.DisFileSever value = null;

  public DisFileSeverHolder ()
  {
  }

  public DisFileSeverHolder (FileSystemApp.DisFileSever initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemApp.DisFileSeverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemApp.DisFileSeverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemApp.DisFileSeverHelper.type ();
  }

}
